--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

-- Started on 2024-07-04 12:00:16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 17460)
-- Name: events; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.events (
    id bigint NOT NULL,
    capacity integer NOT NULL,
    date timestamp(6) without time zone,
    details character varying(255),
    location character varying(255),
    price integer NOT NULL,
    thumbnail character varying(255),
    title character varying(255),
    type character varying(255),
    host_id bigint
);


ALTER TABLE public.events OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 17459)
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 17468)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    password character varying(255),
    role character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 17467)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4842 (class 0 OID 17460)
-- Dependencies: 216
-- Data for Name: events; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.events (id, capacity, date, details, location, price, thumbnail, title, type, host_id) FROM stdin;
2	200	2024-07-02 14:51:42.779796	Annual tech conference featuring startup owners.	Virtual	0	http://example.com/image2.jpg	Startup Conference: Initial phases	Virtual	2
8	300	2024-07-02 15:18:26.234645	Conference discussing the future of sports technology.	Virtual	200	http://example.com/sports_summit.jpg	Sports Summit 2024	Virtual	1
9	300	2024-07-02 17:20:43.899802	Conference discussing the future of sports technology.	Virtual	200	http://example.com/sports_summit.jpg	Sports Summit 2024	Virtual	1
11	100	2024-07-03 11:42:15.810923	This is a sample event.	Sample Location	50	uploads\\1719987135811_DFD-1 Student.png	Sample Event	In-Person	1
12	1002	2024-07-03 11:45:00.606383	This is a sample event 2.	Sample Location 2	502	uploads\\1719987300606_react example.png	Sample Event 2	In-Person 2	1
\.


--
-- TOC entry 4844 (class 0 OID 17468)
-- Dependencies: 218
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, first_name, last_name, password, role) FROM stdin;
1	nilkanth@gmail.com	Nilkanth	Admin	$2a$10$LSTfM6PxAPhmJk9.LnAVruMss8wnL065M8eQM1YEQ7B/ACqtv7EGq	ADMIN
2	nandu@gmail.com	Nandu	Organizer	$2a$10$xtYMomdhOk0HepWtmUAbYu6znPtgS/8lM9MFYK9R7tnAsQLWo0lhq	ORGANIZER
3	zeel@gmail.com	Zeel	Desai	$2a$10$AF.ZdcsBub8m1kjEhfIPaue5HkgN9PkM5a2vZDwrkkb5iqkMWMYbe	USER
\.


--
-- TOC entry 4850 (class 0 OID 0)
-- Dependencies: 215
-- Name: events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.events_id_seq', 12, true);


--
-- TOC entry 4851 (class 0 OID 0)
-- Dependencies: 217
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 3, true);


--
-- TOC entry 4694 (class 2606 OID 17466)
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- TOC entry 4696 (class 2606 OID 17474)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4697 (class 2606 OID 17475)
-- Name: events fknsvyk08eqkdlxp4d2httg2u8v; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fknsvyk08eqkdlxp4d2httg2u8v FOREIGN KEY (host_id) REFERENCES public.users(id);


-- Completed on 2024-07-04 12:00:16

--
-- PostgreSQL database dump complete
--

